#!/bin/bash
# delete an rt or multiple rt tickets
# useful for spam mails sent to rt

### sanity checks
if [ -z "$1" ]
then
        echo "No ticket number supplied as first argument with this script, (will accept multiple tickets), exiting..."
        exit 0
fi

### envirnoment control
export RTSERVER=
if [ -z $RTUSER ]; then
        read -r -p "Please enter your RT username: " username
        export RTUSER=$username
fi
rt=/opt/rt4/bin/rt
date=$(date)
log=/var/log/rt/deleted-tickets.log

### functions
function delete_ticket {
	local ticket=$1
	$rt edit ticket/$ticket set status='deleted'
}

### workflow
for ticket in "$@"
do
	echo "$date - Deleting Ticket $ticket"
	echo "$date - Deleting Ticket $ticket by $RTUSER" >> tickets-deleted.log
	delete_ticket $ticket
done

exit 0
