#!/bin/bash
# merge RT ticket(s)
rt=/opt/rt4/bin/rt
### envirnoment control
export RTSERVER=
if [ -z $RTUSER ]; then
        read -r -p "Please enter your RT username: " username
        export RTUSER=$username
fi

echo "please enter the ticket number for the ticket to be merged INTO"
read -r -p "i.e. the other ticket(s) will be merged into this ticket: " master

# workflow
declare -a tickets=()
while IFS= read -r -p "Ticket(s), (1 per line), to be merged into $master, (end with an empty line): " line; do
    [[ $line ]] || break  # break if line is empty
    tickets+=("$line")
done

for ticket in "${tickets[@]}"; do
	echo "merging $ticket into $master"
	$rt merge $ticket $master
done

exit 0
