#!/bin/bash
# resolve an RT ticket from the CLI, or multiple tickets
rt=/opt/rt4/bin/rt
date=$(date)
log=/var/log/rt/tickets-resolved.log
### sanity check's
if [ -z "$1" ]
then
        echo "No ticket number supplied as first argument with this script, (will accept multiple tickets), exiting..."
        exit 0
fi

### envirnoment control
export RTSERVER=

if [ -z $RTUSER ]; then
	read -r -p "Please enter your RT username: " username
	export RTUSER=$username
fi

### functions
function resolve_ticket {
	local ticket=$1
	echo "Resolving Ticket $ticket"
	echo "$date - Resolving Ticket $ticket by $RTUSER" >> $log
	$rt edit ticket/$ticket set status='resolved'
}

### workflow
for ticket in "$@"
do
	resolve_ticket $ticket
done

exit 0
